---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: 
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Photos
  - Calendar
  - Contacts
  - Reminders
  - Music
  - Podcasts
  - News
  - Keynote
  - Numbers
  - Pages
  - Safari
  - Mail
dockitems_persist:
- name: "Microsoft Edge"
  path: "/Applications/Microsoft Edge.app/"
  pos: 1
- name: "Messages"
  path: "/Applications/Messages.app/"
  pos: 2
- name: "FaceTime"
  path: "/Applications/FaceTime.app/"
  pos: 3
- name: "Maps"
  path: "/Applications/Maps.app/"
  pos: 4
- name: "Microsoft Outlook"
  path: "/Applications/Microsoft Outlook.app/"
  pos: 5
- name: "Microsoft PowerPoint"
  path: "/Applications/Microsoft PowerPoint.app/"
  pos: 6
- name: "Microsoft Word"
  path: "/Applications/Microsoft Word.app/"
  pos: 7
- name: "Microsoft PowerPoint"
  path: "/Applications/Microsoft PowerPoint.app/"
  pos: 8
- name: "Microsoft Excel"
  path: "/Applications/Microsoft Excel.app/"
  pos: 9
- name: "Microsoft OneNote"
  path: "/Applications/Microsoft OneNote.app/"
  pos: 10
- name: "Microsoft Teams"
  path: "/Applications/Microsoft Teams.app/"
  pos: 11
- name: "iTerm"
  path: "/Applications/iTerm.app/"
  pos: 12
- name: "Kui"
  path: "/Applications/Kui.app/"
  pos: 13
- name: "Visual Studio Code"
  path: "/Applications/Visual Studio Code.app/"
  pos: 14
- name: "GoLand"
  path: "/Applications/GoLand.app/"
  pos: 15
- name: "GitKraken"
  path: "/Applications/GitKraken.app/"
  pos: 16
- name: "Kui"
  path: "/Applications/Kui.app/"
  pos: 17
- name: "Lens"
  path: "/Applications/Lens.app/"
  pos: 18
- name: "Zoom"
  path: "/Applications/zoom.us.app/"
  pos: 19
- name: "LastPass"
  path: "/Applications/LastPass.app/"
  pos: 20
- name: "System Preferences"
  path: "/Applications/System Preferences.app/"
  pos: 20

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/garysu/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .osx
  - .gitconfig
  - .aliases
  - .vscode
  

homebrew_installed_packages:
  - autoconf
  - gettext
  - git
  - go
  - gpg
  - httpie
  - iperf
  - kubectl
  - libevent
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - zsh
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - app-cleaner
  - balenaetcher
  - downie
  - eddie
  - evernote
  - grammarly
  - gitkraken
  - goland
  - iterm2
  - kodi
  - kui
  - lastpass
  - lens
  - little-snitch
  - macdown
  - microsoft-edge
  - microsoft-office
  - microsoft-teams
  - openscad
  - permute
  - raspberry-pi-imager
  - slack
  - snagit
  - vagrant
  - visual-studio-code
  - vlc
  - vmware-fusion
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
